theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = false

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 4

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spacer", "file-name", "file-modification-indicator"]
center = []
right = ["spinner", "diagnostics", "selections", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true
