theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "always"
auto-format = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 4

[editor.indent-guides]
render = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "separator", "file-name"]
center = []
right = ["spinner", "diagnostics", "selections", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = " Normal"
mode.insert = " Insert"
mode.select = " Select"

[keys.normal]
C-p = "file_picker"
